EfCoreRegistrationForm/Models/Answer.cs
namespace EfCoreRegistrationForm.Models
{
    public class Answer
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int QuestionId { get; set; }
        public Question Option { get; set; }
    }
}

EfCoreRegistrationForm/Models/ErrorViewModel.cs
using System;

namespace EfCoreRegistrationForm.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EfCoreRegistrationForm/Models/Question.cs
using System.Collections.Generic;

namespace EfCoreRegistrationForm.Models
{
    public class Question
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Answer> Options { get; set; }
    }
}

EfCoreRegistrationForm/Models/QuestionAnswer.cs
namespace EfCoreRegistrationForm.Models
{
    public class QuestionAnswer
    {
        public int RegistrationId { get; set; }
        public int QuestionId { get; set; }
        public Question Question { get; set; }
        public int AnswerId { get; set; }
        public Answer Answer { get; set; }
    }
}

EfCoreRegistrationForm/Controllers/HomeController.cs
using EfCoreRegistrationForm.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EfCoreRegistrationForm.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EfCoreRegistrationForm/Controllers/RegistrationFormController.cs
using EfCoreRegistrationForm.Data;
using EfCoreRegistrationForm.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace EfCoreRegistrationForm.Controllers
{
    public class RegistrationFormController : Controller
    {
        private readonly DataContext _context;

        public RegistrationFormController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var questionsWithAnswersIds = _context.QuestionAnswers.Select(s => s.QuestionId).ToList();

            var questionsWithNoAnswers = _context.Questions.Include(q => q.Options).Where(q => !questionsWithAnswersIds.Contains(q.Id)).ToList();

            var questionAnswers = _context.QuestionAnswers.Include(qa => qa.Question).ThenInclude(q => q.Options).Include(qa => qa.Answer).ToList();

            foreach (var question in questionsWithNoAnswers)
            {
                questionAnswers.Add(new Models.QuestionAnswer()
                {
                    Question = question,
                    QuestionId = question.Id
                });
            }

            var regForm = new RegistrationFormDto()
            {
                QuestionAnswers = questionAnswers
            };
            return View(regForm);
        }
        //public IActionResult EditForm(int id)
        //{
        //    var questionAnswers = _context.QuestionAnswers.Include(c => c.Question).
        //        ThenInclude(q => q.Options);

        //    if (id !=0)
        //    {
        //        questionAnswers.Where(r => r.RegistrationId == id);
        //    }

        //    var RegistrationFormDto = new RegistrationFormDto()
        //    {
        //        QuestionAnswers = questionAnswers.ToList()
        //    };

        //    return View(RegistrationFormDto);
        //}
        [HttpPost]
        public IActionResult UpdateForm(RegistrationFormDto registrationForm)
        {

            if (registrationForm.RegistrationId != null)
            {
                foreach (var question in registrationForm.QuestionAnswers)
                {

                    _context.QuestionAnswers.Update(question);
                }

            }

            //var tmpRng = _context.CompanyBrokers.Where(b => b.BrokerId == brokerCreate.Broker.Id);
            //_context.CompanyBrokers.RemoveRange(tmpRng);

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

EfCoreRegistrationForm/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EfCoreRegistrationForm/Views/RegistrationForm/Index.cshtml
@model EfCoreRegistrationForm.Dtos.RegistrationFormDto

@{
    ViewData["Title"] = "Index";
}
@using (Html.BeginForm("UpdateForm", "RegistrationForm", FormMethod.Post))
{

    <div class="container">

        <h3 class="mb-5"> Registracijos požymiai</h3>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Registracijos požymiai</th>
                    <th scope="col">Reikšmė</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.QuestionAnswers.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.QuestionAnswers[i].Question.Name
                        </td>

                        @Html.HiddenFor(aq => aq.RegistrationId)


                        <td>
                            <div class="disabled">
                                @Html.DropDownListFor(a => Model.QuestionAnswers[i].AnswerId, new SelectList(Model.QuestionAnswers[i].Question.Options, "Id", "Text"),
                                new { @class = "disabled" })

                            </div>
                        </td>
                    </tr>
                }
                @*@foreach (var question in @Model.QuestionAnswers)
                    {
                        <tr>
                            <td>
                                @question.Question.Name
                            </td>
                            <td>
                                @Html.HiddenFor(aq => aq.RegistrationId)
                            </td>

                            <td>
                                <div class="disabled">
                                    @Html.DropDownListFor(a => question.AnswerId, new SelectList(question.Question.Options, "Id", "Text"),
                                    new { @class = "disabled" })

                                </div>
                            </td>
                        </tr>
                    }*@
            </tbody>
        </table>

        <button id="edit" type="button" class="bg-primary">Koreguoti požymius</button>
        <button class="disabled badge-info" type="submit" disabled>Saugoti pataisymus</button>
        <button id="reset" class="disabled" type="reset" disabled>Atšaukti pataisymus</button>

        <script>
            var form = document.getElementById('form');
            var editButton = document.getElementById('edit');
            var resetButton = document.getElementById('reset');
            var initDisabledElements = document.getElementsByClassName('disabled');


            for (var element of initDisabledElements) {

                element.disabled = true;

            }

            editButton.addEventListener('click', function () {
                for (var element of initDisabledElements) {
                    element.disabled = false;
                    editButton.disabled = true;
                }
            });

        </script>

    </div>
}

EfCoreRegistrationForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfCoreRegistrationForm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Registracijos Forma</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegistrationForm" asp-action="Index">Registracija</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EfCoreRegistrationForm - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>